### PR TITLE
Feat: Heroku deployment working version

### PR DESCRIPTION
**Pull request by Bonny88**
HI Gregor,

I have updated this branch with the deployment guide for heroku. 
Please note that this guide works only when used on the main branch of your local repository (you can detach the remote origin and merge main from this branch locally to try)

I've already tried on a fresh heroku application and it seems to work for me.

Best Regards
Bonny

### CODE REVIEW

**Comment by gregorwolf** [comment]
Maybe we should use a [Configuration Profile](https://cap.cloud.sap/docs/node.js/cds-env#profiles) for heroku instead of a separate package.json. What do you think @Bonny88 ?

**Comment by Bonny88** [comment]
Yes, I think that could be a better solution!
I'll update the solution using your suggestion and update the PR

**Comment by Bonny88** [comment]
Hi @gregorwolf 
I have updated my local version to use the profiles as suggested and it's working. However, this feature seems to be unavailable in the @sap/cds version referred by your project (5.1.X).

I have updated my local version to 5.7.1 to have the --profile option on the cds CLI, but i'm aware that this is going to be a breaking change until a new version of cds-dbm is released on npm (see our fix on  mikezaschka/cds-dbm#101)

Should i try with an older version of @sap/cds?  Wich one do you suggest?

Thanks
Bonny

**Comment by gregorwolf** [comment]
Hi @Bonny88,

thank you for your effort. In the meantime you could already update to 5.7.2 :-). I've reached out to @mikezaschka and will hopefully find a way to get cds-dbm soon updated.

CU
Gregor

**Comment by Bonny88** [comment]
Well, this was an unexpected plot twist :D 

The solution seems to work with the latest version as well. I've pushed my local changes to the remote branch and updated the readme file to reflect the procedure changes and the open points.

Thanks again for the work on this project
CU

Bonny

**Review by gregorwolf — APPROVED** [review]

**Comment by gregorwolf** [comment]
@Bonny88 are you on Twitter? I want to give you a shout out and make the possibility to run CAP on Heroku visible.

**Comment by Bonny88** [comment]
Thanks @gregorwolf! 
I took the opportunity to create a new twitter account (https://twitter.com/Bonny1288). 
You can also reach me on linkedin (https://www.linkedin.com/in/luca-bonetta-864262192/)

CU
Bonny

**Pull request merged**
